apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-lab
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ammarun11/odoo-githubActions-lab.git
    targetRevision: HEAD
    path: deployment-odoo-source
  destination: 
    server: https://kubernetes.default.svc
    namespace: odoo-lab

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true