apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: odoo-lab
  labels:
    app: postgres
data:
  POSTGRES_DB: odoodb
  POSTGRES_USER: root
  POSTGRES_PASSWORD: gladiators88
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
  namespace: odoo-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1-bullseye # Sets Image
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgresql-data-db-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  namespace: odoo-lab
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgres